baseURL = 'https://apaleja.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ghostwriter'

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Hello !!! I am ANAND PALEJA !"
    description = "My description"
    github = "https://github.com/XXX"
    twitter = "https://twitter.com/XXX"
    email = "anand.paleja@hotmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
